#!/bin/bash

PROJECT=`grep defproject project.clj | awk '{print $2}'`
v=`grep defproject project.clj | awk '{print $3}'`
VERSION=${v//\"/}

DOMAIN="com.rentpath"

DOMAIN_PATH=${DOMAIN//./\/} 
CMD="install_${PROJECT}.sh"
ARTIFACT="${PROJECT}-${VERSION}.jar"
ARTIFACT_PATH="`pwd`/target/${ARTIFACT}"
REMOTE_HOST="ec2-54-224-24-95.compute-1.amazonaws.com"

if [[ ($1 == "-h") || ($1 == "--help") || ($1 == "") ]]
then
  echo ""
  echo "Load $ARTIFACT into a local or remote Maven repository."
  echo ""
  echo "Usage: load_repository <options>"
  echo ""
  echo "Options:"
  echo ""
  echo "  -l, --local   # Load $ARTIFACT file into local Maven repository ~/m2/repository/$DOMAIN_PATH/$ARTIFACT"
  echo "  -r, --remote  # Load $ARTIFACT file into the remote repository on $REMOTE_HOST:/public/maven/.m2/$DOMAIN_PATH/$PROJECT/$ARTIFACT"
  echo ""
  exit 0
fi

lein uberjar

if [[ ($1 == "-l") && ($1 == "--local") ]]
then
  echo "Installing $ARTIFACT into local Maven repository ..."
  mvn install:install-file -DgroupId=$DOMAIN -DartifactId=$PROJECT -Dversion=$VERSION -Dpackaging=jar -Dfile=$ARTIFACT_PATH -DgeneratePom=true -DcreateChecksum=true
fi

if [[ ($1 == "-r") && ($1 == "--remote") ]]
  echo "Installing $ARTIFACT into remote Maven repository ..."
  tee << EOF > $CMD
mvn install:install-file -DgroupId=$DOMAIN -DartifactId=$PROJECT -Dversion=$VERSION -Dpackaging=jar -Dfile=$ARTIFACT -DgeneratePom=true -DcreateChecksum=true
EOF
  scp -p $CMD $REMOTE_HOST:/public/maven
  ssh ${REMOTE_HOST} "chmod 775 /public/maven/$CMD ; chgrp wheel /public/maven/$CMD"
  scp $ARTIFACT_PATH $REMOTE_HOST:/public/maven
  ssh ${REMOTE_HOST} "chmod 775 /public/maven/$ARTIFACT ; chgrp wheel /public/maven/$ARTIFACT"
  ssh $REMOTE_HOST "cd /public/maven ; ./$CMD ; rm $ARTIFACT $CMD"
  rm $CMD
fi
